# Site settings
title: Southeastern
client:
  name: Southeastern
  link: https://www.southeasternrailway.co.uk/destinations-and-offers/offers
core-se-link: https://www.secretescapes.com/current-sales
description: >
  From micropubs to indie boutiques, discover our Secret Guide to the South East with Southeastern.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/southeastern" # the subpath of your site, e.g. /blog/
img:     "/southeastern/_assets/img"
css:     "/southeastern/_assets/css"
js:      "/southeastern/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed